var videoItems = 
{
  "clips" : [
    {"name": "Ка-тет feat Oxxxymiron - Машина Прогресса (2017)",
    "src": "http://www.youtube.com/embed/AgPyyMUfjXQ",
    "img": "AgPyyMUfjXQ"},
    {"name": "Би-2 feat. Oxxxymiron - Пора возвращаться домой",
    "src": "http://www.youtube.com/embed/2FCF7HvX2fM",
    "img": "2FCF7HvX2fM"},
    {"name": "Markul feat Oxxxymiron - FATA MORGANA (2017)",
    "src": "http://www.youtube.com/embed/d8e9sw6_oec",
    "img": "d8e9sw6_oec"},
    {"name": "Oxxxymiron - Город под подошвой (2015)",
    "src": "http://www.youtube.com/embed/XBleNfmkScA",
    "img": "XBleNfmkScA"},
    {"name": "ЛСП & Oxxxymiron - Безумие (Remix)",
    "src": "http://www.youtube.com/embed/GRvRIS--JRo",
    "img": "GRvRIS--JRo"},
    {"name": "Rigos feat. Oxxxymiron - Дежавю",
    "src": "http://www.youtube.com/embed/CJVpDJ3dFv4",
    "img": "CJVpDJ3dFv4"},
    {"name": "I1 feat Oxxxymiron - Честно (Q-Unique instrumental)",
    "src": "http://www.youtube.com/embed/XTqG_ktgchY",
    "img": "XTqG_ktgchY"},
    {"name": "XXX SHOP (Oxxxymiron, Chronz, Porchy)",
    "src": "http://www.youtube.com/embed/J3_UmPJWQfg",
    "img": "J3_UmPJWQfg"},
    {"name": "Oxxxymiron - Признаки жизни",
    "src": "http://www.youtube.com/embed/tV7xNtLD1wM",
    "img": "tV7xNtLD1wM"},
    {"name": "Oxxxymiron - Не от мира сего",
    "src": "http://www.youtube.com/embed/FPyUFj9tmrE",
    "img": "FPyUFj9tmrE"},
    {"name": "Oxxxymiron - Песенка Гремлина",
    "src": "http://www.youtube.com/embed/c07INIJfNRM",
    "img": "c07INIJfNRM"},
    {"name": "Oxxxymiron - Детектор Лжи",
    "src": "http://www.youtube.com/embed/FxtrqGXY37g",
    "img": "FxtrqGXY37g"},
    {"name": "Oxxxymiron - Хитиновый Покров / Пролив Дрейка",
    "src": "http://www.youtube.com/embed/MohUdHkH46E",
    "img": "MohUdHkH46E"}
  ],
  "battles" : [
    {"name": "KOTD - Oxxxymiron (RUS) vs Dizaster (USA) | #WDVII",
    "src": "http://www.youtube.com/embed/ldK9qvRBkMI",
    "img": "ldK9qvRBkMI"},
    {"name": "VERSUS X #SLOVOSPB: Oxxxymiron VS Слава КПСС (Гнойный)",
    "src": "http://www.youtube.com/embed/v4rvTMBCJD0",
    "img": "v4rvTMBCJD0"},
    {"name": "VERSUS #1 (сезон III): Oxxxymiron VS Johnyboy",
    "src": "http://www.youtube.com/embed/MVouMFKmaeI",
    "img": "MVouMFKmaeI"},
    {"name": "VERSUS #5 (сезон III): Oxxxymiron VS ST",
    "src": "http://www.youtube.com/embed/gGuYELy8w6s",
    "img": "gGuYELy8w6s"},
    {"name": "VERSUS #3: Oxxxymiron VS Крип-А-Крип",
    "src": "http://www.youtube.com/embed/pvKYnii4clY",
    "img": "pvKYnii4clY"},
    {"name": "Versus Main Event #1 (сезон II): Дуня VS Oxxxymiron",
    "src": "http://www.youtube.com/embed/icdl_Fjj3pk",
    "img": "icdl_Fjj3pk"}
  ],
  "interview": [
    {"name": "Oxxxymiron: I Dissed Older Russian Rappers Early in My Career (Part 2)",
    "src": "http://www.youtube.com/embed/--FVmNzgDU4",
    "img": "--FVmNzgDU4"},
    {"name": "Oxxxymiron on Leaving Russia as Communism Fell, Starting to Rap at 13 (Part 1)",
    "src": "http://www.youtube.com/embed/i8VSguDaXfo",
    "img": "i8VSguDaXfo"},
    {"name": "OXXXYMIRON Talks EMINEM, Beating DIZASTER , Mumble Rap and More!",
    "src": "http://www.youtube.com/embed/kwKWf6G4FvY",
    "img": "kwKWf6G4FvY"},
    {"name": "Oxxxymiron Talks Battle With Dizaster, Rapping In English & Russian Fam",
    "src": "http://www.youtube.com/embed/ig8fjfeHeSA",
    "img": "ig8fjfeHeSA"},
    {"name": "Вечерний Ургант - Андрей Воробьёв, Oxxxymiron - 563 выпуск от 09.12.2015",
    "src": "http://www.youtube.com/embed/OujDs7s6wqs",
    "img": "OujDs7s6wqs"}
  ],
  "toor_video": [
    {"name": "IMPERIVM TOUR diaries / Часть 3: Екатеринбург, Самара, Казань",
    "src": "http://www.youtube.com/embed/yDgFsdcTiSY",
    "img": "yDgFsdcTiSY"},
    {"name": "IMPERIVM TOUR diaries / Часть 2: Москва, Иркутск, Новосибирск",
    "src": "http://www.youtube.com/embed/bbeh-dK5Dig",
    "img": "bbeh-dK5Dig"},
    {"name": "IMPERIVM TOUR diaries / Часть 1: Санкт-Петербург",
    "src": "http://www.youtube.com/embed/Uhptv0VLp5M",
    "img": "Uhptv0VLp5M"},
    {"name": "Oxxxymiron - Девочка Пиздец Live in Kiev 23/11/2016",
    "src": "http://www.youtube.com/embed/ptrZ_mCgxtk",
    "img": "ptrZ_mCgxtk"},
    {"name": "BACK TO EUROPE TOUR / TEASER 9: PARIS",
    "src": "http://www.youtube.com/embed/41AlmULFIk4",
    "img": "41AlmULFIk4"},
    {"name": "BACK TO EUROPE TOUR / TEASER 8: COLOGNE",
    "src": "http://www.youtube.com/embed/vKgaP2f8wyA",
    "img": "vKgaP2f8wyA"},
    {"name": "BACK TO EUROPE TOUR / TEASER 7: PRAGUE, HAMBURG, BERLIN",
    "src": "http://www.youtube.com/embed/Q0Oa9B3Rgv0",
    "img": "Q0Oa9B3Rgv0"},
    {"name": "BACK TO EUROPE TOUR / TEASER 6: KRAKOW",
    "src": "http://www.youtube.com/embed/OJeJI4SV894",
    "img": "OJeJI4SV894"},
    {"name": "BACK TO EUROPE TOUR / TEASER 5: WARSAW",
    "src": "http://www.youtube.com/embed/vvhRrBweqHU",
    "img": "vvhRrBweqHU"},
    {"name": "BACK TO EUROPE TOUR / TEASER 4: KALININGRAD",
    "src": "http://www.youtube.com/embed/fvjCXLTIt2o",
    "img": "fvjCXLTIt2o"},
    {"name": "BACK TO EUROPE TOUR / TEASER 3: VILNIUS",
    "src": "http://www.youtube.com/embed/bFzrutuZ72w",
    "img": "bFzrutuZ72w"},
    {"name": "BACK TO EUROPE TOUR / TEASER 2: RIGA",
    "src": "http://www.youtube.com/embed/YvnyPA3uf7E",
    "img": "YvnyPA3uf7E"},
    {"name": "BACK TO EUROPE TOUR / TEASER 1: TALLINN",
    "src": "http://www.youtube.com/embed/w8rqANfXWRM",
    "img": "w8rqANfXWRM"}
  ],
  "other_video": [
    {"name": "FATA MORGANA - MAKING-OF (2017)",
    "src": "http://www.youtube.com/embed/ylSsyloPW_g",
    "img": "ylSsyloPW_g"},
    {"name": "Oxxxymiron сыграет Митру в фильме Empire V (Анонс 2017)",
    "src": "http://www.youtube.com/embed/E-RMCNqzS80",
    "img": "E-RMCNqzS80"},
    {"name": "Reebok Classic x Oxxxymiron x IMPERIVM",
    "src": "http://www.youtube.com/embed/zWQaktqyAJc",
    "img": "zWQaktqyAJc"},
    {"name": "Неожиданное появление Oxxxymiron на встрече слушателей",
    "src": "http://www.youtube.com/embed/v3zYlXngVc0",
    "img": "v3zYlXngVc0"},
    {"name": "Oxxxymiron про ЛСП и трек 'Imperial' (05/04/2016)",
    "src": "http://www.youtube.com/embed/pf-u-FBDy_4",
    "img": "pf-u-FBDy_4"}
  ]
}

$(document).ready(function() {

var source   = document.getElementById("video_block").innerHTML,
    template = Handlebars.compile(source),
    context = videoItems,
    html    = template(context);
$('.video').append(html);

$('.video_click').each(function() {
    $(this).click(function() {
        var $video = $(this).attr('src');
        $('iframe').attr('src', $video);
    });
});

});